#!/bin/bash


CLIENT_ID=$(cat /home/$(whoami)/.spt_client_id)
CLIENT_SECRET=$(cat /home/$(whoami)/.spt_client_secret)

ACCESS_TOKEN=""

get_access_token() {
    RESPONSE=$(curl -X POST \
        "https://accounts.spotify.com/api/token"                \
        -H "Content-Type: application/x-www-form-urlencoded"   \
        -d "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}" 2> /dev/null)
    ACCESS_TOKEN=$(echo ${RESPONSE} | jq -r "${RESPONSE}.access_token")
}

get_access_token

MEHNERSMOOS="4v1lRzkxvSsxo1JVUxXEOK"
ARSCHRAPPER="6F0DDT5azM2RNtuDGM2C6o"
NORMALE_FREUNDE="1PZ1eFifOxsx8SN8YHa0L7"
SIP="a8bc568987febcc1d5124d576cac4d52"
REQUEST=${1}

RESPONSE=$(curl "https://api.spotify.com/v1/artists/${MEHNERSMOOS}" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" 2> /dev/null)

echo "$RESPONSE" | jq
