# vim: filetype=i3config

# playercontrol
bindsym $mod+Mod1+Space exec ~/.config/sway/scripts/play-pause
bindsym $mod+Mod1+d exec playerctl next
bindsym $mod+Mod1+a exec playerctl previous

# setting aplitude
bindsym $mod+Mod1+w exec pactl set-sink-volume \@DEFAULT_SINK@ +2.5%
bindsym $mod+Mod1+s exec pactl set-sink-volume \@DEFAULT_SINK@ -2.5%

bindsym $mod+Mod1+0 exec ~/.config/sway/scripts/songadd
bindsym $mod+Mod1+p exec ~/.config/sway/scripts/open-playlist-modal
bindsym $mod+Mod1+Shift+p exec ~/.config/sway/scripts/open-playlist-modal refresh

# setting different sound outputs
bindsym $mod+Mod1+1 exec pactl set-default-sink alsa_output.usb-GeneralPlus_USB_Audio_Device-00.analog-stereo
bindsym $mod+Mod1+2 exec pactl set-default-sink alsa_output.usb-RODE_Microphones_RODE_NT-USB-00.analog-stereo


set $session " Lock     Exit     Reboot     Poweroff"
mode  $session {
         bindsym e exec --no-startup-id i3-msg exit; mode "default"
         bindsym l exec --no-startup-id ~/.config/i3/blur-lock.sh -e;mode "default"
         bindsym p exec --no-startup-id systemctl poweroff; mode "default"
         bindsym r exec --no-startup-id systemctl reboot; mode "default"

         bindsym q mode "default"
         bindsym Escape mode "default"
}

bindsym $mod+Shift+e mode $session
