# vim: filetype=i3config

bindsym $mod+mod1+i exec qutebrowser

# Windows Hello goofy aah...
bindsym $mod+p exec ~/.config/sway/scripts/startup.sh
bindsym $mod+Shift+Escape exec shutdown now

bindsym Print exec $screenclip
