# vim: filetype=i3config

set $screen1 output DP-1
set $screen2 output HDMI-A-1

set $ws1 "1:Main|Terminal"
set $ws2 "2:Musik"
set $ws3 "3:Brauser"
set $ws4 "4:Talk & Chat"
set $ws5 "5:Steam"
set $ws6 "6:Gaming"
set $ws7 "7:etc"
set $ws8 "8:etc"
set $ws9 "9:etc"
set $ws10 "10:etc"

assign [app_id="foot"] workspace $ws1
assign [app_id="spotify-picker"] workspace $ws1
assign [app_id="spotify"] workspace $ws2
assign [app_id="brave-browser"] workspace $ws3
assign [app_id="org.telegram.desktop"] workspace $ws4
assign [class="discord"] workspace $ws4
assign [app_id="vesktop"] workspace $ws4
assign [class="steam"] workspace $ws5

workspace $ws1 $screen1
workspace $ws2 $screen2
workspace $ws3 $screen2
workspace $ws4 $screen2
workspace $ws5 $screen1

for_window [app_id="spotify-picker"] floating enable, focus


set $screenshot grim ~/Pictures/Screenshots/Screenshot_$(date +"%Y-%m-%d_%H-%M-%S").png && notify-send "Screenshot saved"
set $screenclip slurp | grim -g - ~/Pictures/Screenshots/Screenshot_$(date +"%Y-%m-%d_%H-%M-%S").png && notify-send "Screenshot saved"

