# vim: filetype=i3config

gaps inner 0
gaps outer 0

output DP-1 bg //home/josh/Platten/x-terne/Bitte Hier Speichern/Downloads/Bilder/Wallpaper/1f8c2ffe17f02a06.jpg fill
output HDMI-A-1 bg //home/josh/Platten/x-terne/Bitte Hier Speichern/Downloads/Bilder/Wallpaper/maxresdefault.jpg fill


set $bg-color           #a27264
set $text-color         #f8f8f2
set $bg-inactive        #44475a
set $bg-bar             #362a28
set $unfocused-text     #bfbfbf
set $bg-urgent          #ff5555

#class                  border          bg              text                indicator
client.focused          $bg-color       $bg-color       $text-color         $bg-color
client.unfocused        $bg-bar         $bg-bar         $unfocused-text     $bg-bar
client.focused_inactive $bg-inactive    $bg-inactive    $text-color         $bg-inactive
client.urgent           $bg-inactive    $bg-urgent      $text-color         $bg-urgent
client.placeholder      $bg-bar         $bg-bar         $text-color         $bg-bar

client.background       $text-color
