#! /bin/zsh
#--------------------------------------------------------------------------------------------
#ALIAS
#--------------------------------------------------------------------------------------------

#Alias for Listings

alias lsb="lsblk -a"
alias lsu="lsusb"

alias s="z ~/.local/bin && clear && lt"

alias rc="nvim ~/.zshrc && source ~/.zshrc && clear"
alias globalias='nvim ~/dotfiles/zsh/global_aliasrc && source ~/dotfiles/zsh/global_aliasrc'

# ls aliases
alias ls='eza --group-directories-first'
alias la='ls --all'
alias ll='ls --long'
alias lla='ll --all'
alias lt='ls --tree'
alias lta='lt --all'

alias inst="sudo dnf install"
alias search="sudo dnf search"

alias blk="lsblk | bat -l conf -p"

alias cd="z"
alias sw="z sway && clear && lt"

alias open="xdg-open"

#Alias for system update

alias inst="sudo apt install"
alias update="sudo apt update"
alias upgrade="sudo apt upgrade -y"
alias up="sudo apt update && upgrade"

#Alias for exitting with quit

alias v="nvim"
alias q="exit"
alias :q="exit"
alias quit="exit"

#Alias fast command for pinging a website

alias pingg="ping factorio.fyfe.today"

#Alias for new article -> LaTeX related; new latex document with article template is created

alias newtex="cp /home/${USER}/JRConfigs/.config/latex/template.tex"

#Shortening to long and common commands

alias mk="mkdir -pv"
alias rsync="rsync -rtvzP"
alias ptf="find . | grep -s"

#Alias for tar

alias taar="tar -czvf"
alias untar="tar --extract -f"

#--------------------------------------------------------------------------------------------
#Alias für Promts
#--------------------------------------------------------------------------------------------

alias stanni="clear && source ~/.zshrc && echo Erledigt! && sleep 1 && clear"
alias fliegen="clear && export PROMPT='%B%F{#800000}[%f%F{#69C0CC}Ich bin%f%F{#069420} ein Flugzeug%f%F{#B0B0B0} ✈ %f%F{#2088B1}%f%F{#2088B1}  %f%F{#800000}]%f%b %B[%F{#33d17a}%~%f%b%B%F{255}]%f%b %B%F{#E9AD0C}${vcs_info_msg_0_}%b%f% '$'\n%B%F{#D7B0B0}[>] %f%b'"
alias c0ck="clear && export PROMPT='%B%F{#FF0000}C%f%F{#FF8200}0%f%F{#FFFF00}c%f%F{#82FF00}k%f%F{#00FF00}m%f%F{#00FF82}e%f%F{#00FFFF}1%f%F{#0082FF}5%f%F{#0000FF}t%f%F{#8200FF}3%f%F{#AA00AA}r%f%b %B%F{#D7B0B0}[%~]%f%b %B%F%f%b%B%b%B${ERRORCOL}'$'[>] %f%b'"
# alias sip="clear && export PROMPT='%B%F{#AA0000}[%f%F{#FF0000}St%f%F{#FFAA00}ay%f%F{#FFFF00} Hy%f%F{#AAFF00}d%f%F{#00FF00}r%f%F{#00FFAA}a%f%F{#00FFFF}t%f%F{#00AAFF}e%f%F{#0000FF}d%f%F{#AA00AA}]%f%b %B[%F{#33d17a}%~%f%b%B%F{255}]%f%b %B%F%f%b%B%b%B${ERRORCOL}'$'[>] %f%b'"
alias lom="clear && export PROMPT='%B%F{255}Du bist %f%F{#CC00FF}%n%f%F{255}. Ich bin n normaler %f%F{#33C7DE}%m%f%F{255}.%b %B%F{#FFD800}[%~]%f%b'$'\n%B%F{#00FF00}[>]%f%b '"
alias unten="clear && export PROMPT='%B%F{#FF0000}U%f%F{#FF8200}n%f%F{#FFFF00}t%f%F{#82FF00}e%f%F{#00FF00}n%f%F{#00FF82} T%f%F{#00FFFF}e%f%F{#0082FF}x%f%F{#0000FF}t%f%F{#8200FF} :%f%F{#AA00AA})%f%b %B%F{#D7B0B0}[%~]%f%b %B%F%f%b%B%b%B${ERRORCOL}'$'[>] %f%b'"
alias harry="clear && export PROMPT='%B╭%b%F{#7daea3}  %f %F{#7daea3}%~%f  ${vcs_info_msg_0_}'$'\n''%B╰%b${ERRORCOL}%B%f%b '"

#--------------------------------------------------------------------------------------------
#SSH-Verbindungen
#--------------------------------------------------------------------------------------------
alias mountServer='sshfs Server:. ~/Platten/Server && cd ~/Platten/Server && ll'

#Alias for funny doas

alias please="sudo"
alias fucking="sudo"
alias diggi="sudo"

# Alias für PHP, ARTISAN, LARAVEL, ETC.
alias pest="./vendor/bin/pest"

alias lama='ollama run llama3.1:8b'

